export const GESTURE_THRESHOLDS = {
  MIN_SWIPE_DISTANCE: 16,
  MIN_SWIPE_EXECUTE_DISTANCE: 48,
  SWIPE_ANGLE_RATIO: 1.2,
} as const;

export const UI_CONFIG = {
  VERSE_VISIBILITY_THRESHOLD: 60,
  ARABIC_LINE_HEIGHT: 36,
  TRANSLATION_LINE_HEIGHT: 20,
} as const;
